apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-processor
  labels:
    app: customer-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-processor
  template:
    metadata:
      labels:
        app: customer-processor
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 3000
        runAsNonRoot: true
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: customer-processor
          image: customer-processor
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 3000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: db-credentials
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: db-credentials
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: db-credentials
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: db-credentials
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: db-credentials
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: secret-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secret-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault-secretprocessor"
              syncSecret.enabled: "true"
