namespace: prod
replicaCount: 1

image:
  repository: customer-ui
  tag: latest
containerPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
