apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secretprocessor
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 1b8828d8-eaa0-4d38-b1d5-74320b3864bb
    keyvaultName: s00181kvna2
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-port
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
    tenantId: d7c1df9a-a532-41cf-9c79-0680e0108ca6
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - key: DB_HOST
          objectName: db-host
        - key: DB_PORT
          objectName: db-port
        - key: DB_NAME
          objectName: db-name
        - key: DB_USER
          objectName: db-user
        - key: DB_PASSWORD
          objectName: db-password
