apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: { { .Chart.Name } }
  ports:
    - port: 80
      targetPort: { { .Values.containerPort } }
  type: ClusterIP
