apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: customeronbordingacr
      api_url: https://customeronbordingacr.azurecr.io
      prefix: customeronbordingacr.azurecr.io
      ping: yes
      credentials: secret:argocd/acr-creds#auth
