name: Build and Push to ACR

on:
  push:
    paths:
      - "Docker/**/Dockerfile"
      - ".github/workflows/build-and-push.yaml"

permissions:
  contents: write

env:
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Stop loop - exit if triggered by GitHub Actions bot
        if: github.actor == 'github-actions[bot]'
        run: |
          echo "Triggered by GitHub Actions bot — exiting to prevent loop"
          exit 0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login using Azure CLI
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push UI image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-ui:${{ env.IMAGE_TAG }} ./Docker/customer-ui
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-ui:${{ env.IMAGE_TAG }}

      - name: Build and push ingestion image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-ingestion:${{ env.IMAGE_TAG }} ./Docker/customer-ingestion
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-ingestion:${{ env.IMAGE_TAG }}

      - name: Build and push processor image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-processor:${{ env.IMAGE_TAG }} ./Docker/customer-processor
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-processor:${{ env.IMAGE_TAG }}
