name: Build and Push Docker Images to AC-R

on:
  push:
    branches:
      - main
    paths:
      - "Docker/customer-ui/**"
      - "Docker/customer-ingestion/**"
      - "Docker/customer-processor/**"
      - ".github/workflows/build-and-push.yaml"

env:
  IMAGE_TAG: ${{ github.run_number }}-${{ github.run_id }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Build and push customer-ui
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-ui:${{ env.IMAGE_TAG }} ./Docker/customer-ui
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-ui:${{ env.IMAGE_TAG }}

      - name: Build and push customer-ingestion
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-ingestion:${{ env.IMAGE_TAG }} ./Docker/customer-ingestion
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-ingestion:${{ env.IMAGE_TAG }}

      - name: Build and push customer-processor
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-processor:${{ env.IMAGE_TAG }} ./Docker/customer-processor
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-processor:${{ env.IMAGE_TAG }}
