name: Build and Deploy to AKS

on:
  push:
    paths:
      - "Docker/**/Dockerfile"
      - ".github/workflows/build-and-push.yaml"

env:
  ACR_NAME: customeronboardingacr
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push UI image
        run: |
          docker build -t $ACR_NAME.azurecr.io/customer-ui:${IMAGE_TAG} ./Docker/customer-ui
          docker push $ACR_NAME.azurecr.io/customer-ui:${IMAGE_TAG}

      - name: Build and push ingestion image
        run: |
          docker build -t $ACR_NAME.azurecr.io/customer-ingestion:${IMAGE_TAG} ./Docker/customer-ingestion
          docker push $ACR_NAME.azurecr.io/customer-ingestion:${IMAGE_TAG}

      - name: Build and push processor image
        run: |
          docker build -t $ACR_NAME.azurecr.io/customer-processor:${IMAGE_TAG} ./Docker/customer-processor
          docker push $ACR_NAME.azurecr.io/customer-processor:${IMAGE_TAG}

      - name: Set image tag in kustomization
        run: |
          cd k8s/overlays/prod
          kustomize edit set image customeronboardingacr.azurecr.io/customer-ui=customeronboardingacr.azurecr.io/customer-ui:${IMAGE_TAG}
          kustomize edit set image customeronboardingacr.azurecr.io/customer-ingestion=customeronboardingacr.azurecr.io/customer-ingestion:${IMAGE_TAG}
          kustomize edit set image customeronboardingacr.azurecr.io/customer-processor=customeronboardingacr.azurecr.io/customer-processor:${IMAGE_TAG}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group customer-onboarding-rg --name customeronboarding-aks
          kubectl apply -k k8s/overlays/prod
