name: Build and Deploy to AKS1

on:
  push:
    paths:
      - "Docker/**/Dockerfile"
      - ".github/workflows/build-and-push.yaml"

env:
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login using Azure CLI
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push UI image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-ui:${{ env.IMAGE_TAG }} ./Docker/customer-ui
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-ui:${{ env.IMAGE_TAG }}

      - name: Build and push ingestion image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-ingestion:${{ env.IMAGE_TAG }} ./Docker/customer-ingestion
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-ingestion:${{ env.IMAGE_TAG }}

      - name: Build and push processor image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer-processor:${{ env.IMAGE_TAG }} ./Docker/customer-processor
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer-processor:${{ env.IMAGE_TAG }}

      - name: Install Kustomize CLI
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin

      - name: Update image tags in kustomization
        run: |
          cd k8s/overlays/prod
          kustomize edit set image customer-ui=${{ secrets.ACR_NAME }}.azurecr.io/customer-ui:${{ env.IMAGE_TAG }}
          kustomize edit set image customer-ingestion=${{ secrets.ACR_NAME }}.azurecr.io/customer-ingestion:${{ env.IMAGE_TAG }}
          kustomize edit set image customer-processor=${{ secrets.ACR_NAME }}.azurecr.io/customer-processor:${{ env.IMAGE_TAG }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group customer-onboarding-rg --name customeronboarding-aks --overwrite-existing
          kubectl apply -k k8s/overlays/prod
